quickfixj:
  client:
    config: file:/opt/app/quickfixj-client.cfg
    jmx-enabled: true

server:
  port: 8080

management:
  endpoint:
    quickfixjclient:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjclient