image:https://travis-ci.org/esanchezros/quickfixj-spring-boot-starter-examples.svg?branch=2.0.x["Build Status",link="https://travis-ci.org/esanchezros/quickfixj-spring-boot-starter-examples"]
image:https://img.shields.io/badge/maven%20central-v2.9.0-blue.svg["Maven Central",link="https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22quickfixj-spring-boot-starter-examples%22"]
image:https://img.shields.io/hexpm/l/plug.svg["Apache 2",link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/badge/quickfixj-2.2.0-blue.svg["QuickFIX/J 2.2.0",link="https://github.com/quickfix-j/quickfixj"]

= Spring Boot Starter Examples for QuickFIX/J (Spring Boot 2)

== Main project

https://github.com/esanchezros/quickfixj-spring-boot-starter[quickfixj-spring-boot-starter]

=== Build the project

    mvn clean install

=== Simple Server Example

The simple server example can be run directly from the IDE or in the command line:

    java -jar simple-server/target/simple-server.jar

=== Simple Server with Application Listener Example

The simple server example can be run directly from the IDE or in the command line:

    java -jar simple-server-listener/target/simple-server-listener.jar

=== Simple Client Example

The simple client example can be run directly from the IDE or in the command line:

    java -jar simple-client/target/simple-client.jar

=== Simple Client with Application Listener Example

The simple client example can be run directly from the IDE or in the command line:

    java -jar simple-client-listener/target/simple-client-listener.jar

=== Docker Examples

To build the docker containers:

    mvn clean install -DskipDocker=false

==== Client-Server

Go to `docker-server-client/src/main/docker` and run:

    docker-compose -f docker-compose.yml up -d

==== Client-Server with Failover

Go to `docker-server-client-with-failover/src/main/docker` and run:

    docker-compose -f docker-compose-failover.yml up -d

If you want to see the failover in action, kill the first server container and see the client reconnecting to the second server after around a minute or so:

    docker rm -f quickfixj-spring-boot-server
