= Spring Boot Starter Examples for QuickFixJ (Spring Boot 2)

== Main project

https://github.com/esanchezros/quickfixj-spring-boot-starter[quickfixj-spring-boot-starter]

=== Build the project

    mvn clean install

=== Simple Server Example

The simple server example can be run directly from the IDE or in the command line:

    java -jar simple-server/target/simple-server.jar

=== Simple Server with Application Listener Example

The simple server example can be run directly from the IDE or in the command line:

    java -jar simple-server-listener/target/simple-server-listener.jar

=== Simple Client Example

The simple client example can be run directly from the IDE or in the command line:

    java -jar simple-client/target/simple-client.jar

=== Simple Client with Application Listener Example

The simple client example can be run directly from the IDE or in the command line:

    java -jar simple-client-listener/target/simple-client-listener.jar

=== Docker Examples

To build the docker containers:

    mvn clean install -DskipDocker=false

==== Client-Server

Go to `docker-server-client/src/main/docker` and run:

    docker-compose -f docker-compose.yml up -d

==== Client-Server with Failover

Go to `docker-server-client-with-failover/src/main/docker` and run:

    docker-compose -f docker-compose-failover.yml up -d

If you want to see the failover in action, kill the first server container and see the client reconnecting to the second server after around a minute or so:

    docker rm -f quickfixj-spring-boot-server
