quickfixj:
  server:
    config: file:/opt/app/quickfixj-server.cfg
    jmx-enabled: true

server:
  port: 8080

management:
  endpoint:
    quickfixjserver:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjserver