# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Send FIX.4.1 - OrderCancelRequest to client
GET http://localhost:8089/send-client-message?fixVersion=FIX.4.1&messageType=OrderCancelRequest

### Send FIXT1.1 - Quote to client
GET http://localhost:8089/send-client-message?fixVersion=FIXT.1.1&messageType=Quote

###

### Send FIX.4.1 - OrderCancelRequest to server
GET http://localhost:8089/send-server-message?fixVersion=FIX.4.1&messageType=OrderCancelRequest

### Send FIXT1.1 - Quote to server
GET http://localhost:8089/send-server-message?fixVersion=FIXT.1.1&messageType=Quote

###